[package]
name = "discord_rust_playground"
version = "0.1.0"
authors = ["vlakreeh <riverserver2012@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10.0-alpha.1", features = ["json"] }
serenity = "0.7.2"
thiserror = "1.0.4"
serde_json = "1.0.41"
serde = { version = "1.0", features = ["derive"] }
tokio = "0.2.0-alpha.6"